"""list panel message id

Revision ID: 9b9e024dd068
Revises: d5cde13bae0c
Create Date: 2026-08-28 10:01:46.858879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9e024dd068'
down_revision: Union[str, Sequence[str], None] = 'd5cde13bae0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panel_message_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_column('panel_message_id')

    # ### end Alembic commands ###
